services:
  - type: web
    name: stadium-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        sync: false # Will be set manually in dashboard
      - key: DATABASE_URL
        sync: false # Will be set manually in dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        sync: false # Set this in dashboard
      - key: EMAIL_HOST_PASSWORD
        sync: false # Set this in dashboard
      - key: DEFAULT_FROM_EMAIL
        sync: false # Set this in dashboard

databases:
  - name: stadium-db
    databaseName: stadium
    plan: free
