services:
  - type: web
    name: stadium-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: stadium-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "stadium-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://stadium-frontend.onrender.com"

databases:
  - name: stadium-db
    databaseName: stadium
    plan: free
