# Generated by Django 5.1.5 on 2025-01-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_api', '0003_remove_reservation_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(max_length=200)),
                ('service_account_path', models.CharField(default='service-account.json', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Settings',
                'verbose_name_plural': 'Calendar Settings',
            },
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='calendar_id',
        ),
        migrations.AddField(
            model_name='stadium',
            name='calendar_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadium_api.calendarsettings'),
        ),
    ]
