# Generated by Django 5.1.5 on 2025-01-20 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_api', '0004_calendarsettings_remove_stadium_calendar_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarsettings',
            options={},
        ),
        migrations.RenameField(
            model_name='stadium',
            old_name='hourly_rate',
            new_name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='calendar_settings',
        ),
        migrations.AlterField(
            model_name='calendarsettings',
            name='calendar_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calendarsettings',
            name='service_account_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
