# Generated by Django 5.1.5 on 2025-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_api', '0007_userprofile_email_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
