# Generated by Django 5.1.5 on 2025-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_api', '0008_remove_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
    ]
