# Generated by Django 5.1.5 on 2025-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_api', '0009_alter_userprofile_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsettings',
            name='service_account_path',
        ),
        migrations.AddField(
            model_name='calendarsettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarsettings',
            name='name',
            field=models.CharField(default='Default Stadium', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_cancellation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
