# Generated by Django 5.1.5 on 2025-01-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_api', '0010_remove_calendarsettings_service_account_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarSettings',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
